### ISSUE TITLE
Hey I have a question

### ISSUE THREAD

**Issue by tobyplowy** [TumeniNodes/mild_64px#1]
Hey my name is toby I'm the Guy Who helped Make The node box tree mod
Your texture pack Looks Amazing and i Maybe interested in helping, can I ask are these textures made by you (did you make Them with a camera) or are they from a website?

**Comment by TumeniNodes** [comment]
Various methods. For instance, the sand, is from a picture of a beach scene on a website..., I literally cropped out a tiny section of the beach part of the photo, and then played with it using xara, gimp, and krita and mixing some dots to give it a slightly grainy look... The grass, I started with a green square and simply messed around adding noise to it until it looked right... it's all just many various and random methods, just what ever. I have changed each texture probably, literally 100 times since I started...
My HDD is literally stuffed with photos I have taken of nature, architecture, etc. as well as random photos I find online, or some things I literally create from nothing.
As I mentioned in the post, items I have not done are covered by default textures, a couple are from the misa texture pack but will be changed (I just replaced the doors from misa with my own, literally just before I posted the TP on the forum)
I am open to help with the tools... I don;t use tools at all so I have zero interest with doing them... but, If someone else does do them, I want them to blend well with the basic theme...

**Comment by tobyplowy** [comment]
@TumeniNodes I Won't Be helping with tools i have just a couple of textures I made for my texture pack (it's dead) so Maybe you can use them ( there's a sword in it)

**Comment by tobyplowy** [comment]
[tex.zip](https://github.com/TumeniNodes/mild_64px/files/681529/tex.zip) give creddit if used

**Comment by TumeniNodes** [comment]
If you'd like to share them I'd be happy to look at them. If i add them (even altered) I will add your part in credits.
maybe the sword will fit in and give someone else a visual to go off for other tools... or not haha

**Comment by TumeniNodes** [comment]
cool, thanks for sharing, I'll check them out later.
btw I have aspen and jungle leaves I want to add to my tp for nbtrees but I want to pass them by you both first before I would add them to post... I'll PM them to you

**Comment by TumeniNodes** [comment]
Im gonna close this issue not so it doesnt appear the pack has a prob ; )

**Comment by tobyplowy** [comment]
@TumeniNodes what?

**Comment by tobyplowy** [comment]
prob?
